language: c
compiler: gcc
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
  - os: linux
    dist: precise
  exclude:
  # try to workaround https://github.com/travis-ci/travis-ci/issues/4681
  - compiler: gcc

before_script: autoreconf -fiv
addons:
  apt:
    packages:
      - libavformat-dev
      - libavcodec-dev
      - libav-tools
      - libavutil-dev
      - libswscale-dev 
      - libjpeg8-dev
      - libv4l-dev 
      - libzip-dev
script: ./configure && make
